# Generated by Django 5.0.1 on 2024-01-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='hora_fin',
            new_name='hora_final',
        ),
    ]
